### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by hydrapolic**
Partially fixes https://github.com/openzipkin/zipkin-gcp/issues/230

### CODE REVIEW

**Comment by shakuzen** [comment]
@hydrapolic could you please allow maintainers to push changes to this pull request so I can add commits to handle other things blocking the CI currently?

**Comment by shakuzen** [comment]
I guess that isn't the problem. I see the pull request is already set to allow maintainers to edit the PR, but I get a permission failure trying to push additional commits to your branch. Perhaps because it is the `master` branch.

**Comment by shakuzen** [comment]
I opened #232 instead

**Comment by shakuzen** [comment]
Closing this in favor of #232

**Comment by hydrapolic** [comment]
Thanks @shakuzen

**Pull request closed without merging**
